[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { workspace = true }
config = { path = "../config" }
utils = { path = "../utils" }
api = { path = "../api" }
tokio = { workspace = true, default-features = false, features = [
    "rt-multi-thread",
    "macros",
    "parking_lot",
    "signal",
] }
#
tracing = { workspace = true, default-features = false }
tracing-appender = { workspace = true, default-features = false }
tracing-subscriber = { workspace = true, default-features = false, features = [
    "json",
    "env-filter",
    "local-time",
    "registry",
] }
